### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by dpsanders** [invenia/FDM.jl#25]
The name `FDM.jl` makes the package un-discoverable.
Perhaps it could be changed to `FiniteDifferences.jl` or similar?

**Comment by jessebett** [comment]
This is a great package that I wish I had discovered earlier. Not sure if I would have with the name changed, but it's possible. FDM.jl isn't very high up on DuckDuckGo results for `Finite Differences Julia` for instance (though Google performs better).

**Comment by willtebbutt** [comment]
Very much pro-this. @iamed2 is this something that you would be happy to arrange?

**Comment by oxinabox** [comment]
This is done and transferred to https://github.com/JuliaDiff/FiniteDifferences.jl
